server:
  port: 8090

spring:
  redis:
    host: '192.168.1.202'
    port: 6379
    timeout: 60000
    database: 12
    password: '123456'


shorturl:
  redirect:
    enable: true
    url-suffix: '/to'
  api:
    enable: true
    url-suffix: '/api'
    add: '/add'
    get: '/get'
  store:
    retryMax: 6
    store-type: redis